use std::fs;

fn main() {
    // Read version from version.txt
    let version = fs::read_to_string("version.txt")
        .expect("Failed to read version.txt")
        .trim()
        .to_string();

    // Generate version.rs file
    let version_content = format!(
        r#"// This file is auto-generated by build.rs
pub const APP_VERSION: &str = "{}";
"#,
        version
    );
    
    fs::write("src/version.rs", version_content)
        .expect("Failed to write version.rs");
    
    // Re-run if version.txt changes
    println!("cargo:rerun-if-changed=version.txt");
    
    // Call tauri-build
    tauri_build::build()
}
